### ISSUE TITLE
Reorganize GitHub Repo

### ISSUE THREAD

**Issue by daveremy** [giladgray/WhichBus#10]
I am not sure whether this is right but it seems like we may need to reorganize the top level of the repo to allow a folder for docs, misc stuff, and have the main rails project one level lower.   Not sure, but putting it out there.

**Comment by giladgray** [comment]
Hmm. There's a Downloads tab under Code that allows us to upload misc files and an entire Wiki section that we haven't really used at all. Maybe we should explore those options before reorganizing the repo itself? I'm worried that changing the folder structure would make git really unhappy.

**Comment by daveremy** [comment]
Sounds good, we can/should postpone until we have a real reason.  I wonder what we might do if, say, we want to do a prototype of something else, or have an iphone app project or something.  Maybe another repo ...

No matter want I never want to make git unhappy :)
