### ISSUE TITLE
Add Google Analytics to demo site

### ISSUE THREAD

**Issue by kimmanis** [giladgray/WhichBus#11]
At some point before we distribute to a wider audience, let's include google analytics code to keep track of activity. This is definitely low priority, but just wanted to add it to the list so we don't forget. 

Copy the following code, then paste it onto every page you want to track immediately before the closing </head> tag. 

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28348026-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

**Comment by paigepauli** [comment]
I was just thinking about this when I woke up this morning! Good call.

**Comment by dalanmiller** [comment]
I'm going to push this to heroku right now!

On Mon, Jan 16, 2012 at 4:34 PM, Kim Manis <
reply@reply.github.com

**Comment by dalanmiller** [comment]
Alright it's on Heroku, let me know if it doesn't work.
