### ISSUE TITLE
ridiculous predictions

### ISSUE THREAD

**Issue by giladgray** [giladgray/WhichBus#12]
Some bus predictions are just absurdly large, on the order of 1000s of days. Need to investigate why and either solve or filter these results.

**Comment by paigepauli** [comment]
Maybe you just discovered time travel??

**Comment by daveremy** [comment]
I joined the one bus away developer group today.  We might be able to ask for clarification there.

**Comment by giladgray** [comment]
Which bus will get me back to the future?

**Comment by giladgray** [comment]
Fixed! predictionTime = 0 causes this. ArrivalDeparture now checks itself for this case and provides scheduled times if necessary.
