### ISSUE TITLE
Map display

### ISSUE THREAD

**Issue by paigepauli** [giladgray/WhichBus#31]
Is it possible to fix the header w/ route and map on the page (but still be able to navigate around it, like we're able to now), and then scroll through the stops on the lower section? Or have the availability to collapse the map if you don't care about viewing it and only want to see buses/stops?

You'll also see on the UI that I'll be sending out shortly, but the journey page header (the gray bar with the departure and arrival) needs to be _much_ smaller (maybe this is obvious to everyone...) so that it's only one or two small lines of text. What is the text size currently at?

**Comment by giladgray** [comment]
Paige, we can do anything! If you can put it in words, chances are good it can happen. But it might take a while.
